version: '2'
services:

  web:
    image: wordpress
    links:
      - mysql
    environment:
      - WORDPRESS_DB_PASSWORD=sample
  #  volumes:
  #    - wordpress/wp_html:/var/www/html
    ports:
      - "8082:80"
    # - "127.0.0.3:8082:80" # Richable only on local
  
    logging:
      driver: syslog
      options:
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
  #        syslog-address: "udp://localhost:5514"
          
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=sample
      - MYSQL_DATABASE=wordpress
    logging:
      driver: syslog
      options:
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
  #      syslog-address: "udp://localhost:5514"
  #  volumes:
  #    - ./mysql/data:/var/lib/mysql
